theme: jekyll-theme-minimal

title: [Xuewen Qian's Page]
description: [This is a home page for showing the research activities, including papers and presentations.]
logo: [Profile_photo_XuewenQian.jpg]
